In [10]:
import numpy as np
import pandas as pd
import random
import copy
from sklearn.datasets import load_iris

In [11]:
data=load_iris()
d=data["data"]

In [12]:
def initial_seed(d,k):
    a=random.randint(1,d.shape[0])
    cluster_point=[""]*k
    dist=-1
    max_dist=0
    temp=0
    for i in range(k):
        if(i==0):
            for j in d:
                di=np.linalg.norm(j-d[a])
                if di>dist:
                    dist=di
                    cluster_point[i]=j
                    temp=j
        else:
            di=[0]*i
            d=np.delete(d,temp,axis=0)
            for j in range(d.shape[0]):
                dist=di
                flag=0
                for m in range(i):
                    dist[m]=np.linalg.norm(j-cluster_point[m])
                for l in range(i):
                    if(di[l]!=dist[l]):
                        flag=1
                        break
                if(flag==0):
                    di=dist
                    cluster_point[i]=d[j]
                    temp=j
    return(cluster_point)

In [13]:
def distance(d,cluster_point):
    dist=np.zeros([d.shape[0],len(cluster_point)])
    for i in range(d.shape[0]):
        for j in range(len(cluster_point)):
            dist[i,j]=np.linalg.norm(d[i]-cluster_point[j])
    return(dist)

In [14]:
def kmean(d,k):
    cluster_point=initial_seed(d,k)
    cluster=[""]*k
    for i in range(k):
        for l in range(k):
            cluster[l]=[]
        dist=distance(d,cluster_point)
        for j in range(dist.shape[0]):
            cluster[np.argmin(dist[j])].append(d[j])
        for l in range(k):
            cluster_point[l]=np.mean(np.array(cluster[l]),axis=0)
    return(cluster)

In [15]:
cluster=kmean(d,5)

/home/acer/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future


In [16]:
cluster

[[array([7.6, 3. , 6.6, 2.1]),
  array([7.3, 2.9, 6.3, 1.8]),
  array([7.7, 3.8, 6.7, 2.2]),
  array([7.7, 2.6, 6.9, 2.3]),
  array([7.7, 2.8, 6.7, 2. ]),
  array([7.2, 3.2, 6. , 1.8]),
  array([7.2, 3. , 5.8, 1.6]),
  array([7.4, 2.8, 6.1, 1.9]),
  array([7.9, 3.8, 6.4, 2. ]),
  array([7.7, 3. , 6.1, 2.3])],
 [array([5.1, 3.5, 1.4, 0.2]),
  array([4.9, 3. , 1.4, 0.2]),
  array([4.7, 3.2, 1.3, 0.2]),
  array([4.6, 3.1, 1.5, 0.2]),
  array([5. , 3.6, 1.4, 0.2]),
  array([5.4, 3.9, 1.7, 0.4]),
  array([4.6, 3.4, 1.4, 0.3]),
  array([5. , 3.4, 1.5, 0.2]),
  array([4.4, 2.9, 1.4, 0.2]),
  array([4.9, 3.1, 1.5, 0.1]),
  array([5.4, 3.7, 1.5, 0.2]),
  array([4.8, 3.4, 1.6, 0.2]),
  array([4.8, 3. , 1.4, 0.1]),
  array([4.3, 3. , 1.1, 0.1]),
  array([5.8, 4. , 1.2, 0.2]),
  array([5.7, 4.4, 1.5, 0.4]),
  array([5.4, 3.9, 1.3, 0.4]),
  array([5.1, 3.5, 1.4, 0.3]),
  array([5.7, 3.8, 1.7, 0.3]),
  array([5.1, 3.8, 1.5, 0.3]),
  array([5.4, 3.4, 1.7, 0.2]),
  array([5.1, 3.7, 1.5, 0.4]),
  array