In [1]:
import numpy as np
import pandas as pd
import random
from sklearn.datasets import load_iris

In [2]:
data=load_iris()
d=data["data"]
d.shape

(150, 4)

In [3]:
def initialize(d,k):
    a=np.random.randint(0,d.shape[0],k)
    seed=[]
    for i in a:
         seed.append(d[i])
    return(seed,list(a))

In [4]:
def distance(seed,d):
    dist=np.zeros([d.shape[0],len(seed)])
    for i in range(d.shape[0]):
        for j in range(len(seed)):
            dist[i,j]=np.linalg.norm(d[i]-seed[j])
    return(dist)

In [8]:
def kmediod(d,k):
    seed,seed_point=initialize(d,k)
    cluster=[""]*k
    dist=distance(seed,d)
    before=[]
    for i in dist:
        before.append(min(i))
    flag=0
    m=0
    while( flag==0):
        score=[]
        for i in range(k):
            for l in range(k):
                 cluster[l]=[]
        while(True):
            a=np.random.randint(0,d.shape[0])
            if(a not in seed_point):
                seed_point.append(a)
                break
        seed[i]=d[a]
        dist=distance(seed,d)
        for j in range(dist.shape[0]):
            cluster[np.argmin(dist[j])].append(d[j])
        after=[]
        for i in dist:
             after.append(min(i))
        score.append(sum(list(np.array(before) - np.array(after))))
        if(all(x<0 for x in score)):
            flag=1     
    return(cluster)

In [9]:
cluster=kmediod(d,5)

In [10]:
cluster

[[array([5.1, 3.5, 1.4, 0.2]),
  array([4.9, 3. , 1.4, 0.2]),
  array([4.7, 3.2, 1.3, 0.2]),
  array([4.6, 3.1, 1.5, 0.2]),
  array([5. , 3.6, 1.4, 0.2]),
  array([5.4, 3.9, 1.7, 0.4]),
  array([4.6, 3.4, 1.4, 0.3]),
  array([5. , 3.4, 1.5, 0.2]),
  array([4.4, 2.9, 1.4, 0.2]),
  array([4.9, 3.1, 1.5, 0.1]),
  array([5.4, 3.7, 1.5, 0.2]),
  array([4.8, 3.4, 1.6, 0.2]),
  array([4.8, 3. , 1.4, 0.1]),
  array([4.3, 3. , 1.1, 0.1]),
  array([5.8, 4. , 1.2, 0.2]),
  array([5.7, 4.4, 1.5, 0.4]),
  array([5.4, 3.9, 1.3, 0.4]),
  array([5.1, 3.5, 1.4, 0.3]),
  array([5.7, 3.8, 1.7, 0.3]),
  array([5.1, 3.8, 1.5, 0.3]),
  array([5.4, 3.4, 1.7, 0.2]),
  array([5.1, 3.7, 1.5, 0.4]),
  array([4.6, 3.6, 1. , 0.2]),
  array([5.1, 3.3, 1.7, 0.5]),
  array([4.8, 3.4, 1.9, 0.2]),
  array([5. , 3. , 1.6, 0.2]),
  array([5. , 3.4, 1.6, 0.4]),
  array([5.2, 3.5, 1.5, 0.2]),
  array([5.2, 3.4, 1.4, 0.2]),
  array([4.7, 3.2, 1.6, 0.2]),
  array([4.8, 3.1, 1.6, 0.2]),
  array([5.4, 3.4, 1.5, 0.4]),
  array(